@echo off
set WD="%~dp0"
goto startCode

===========================================================================
chew-dir_py.bat
ljkrajewski
4/17/2019 11:31:10 AM
=====start powershell code=================================================
function main1 {
  # Requires Cygwin with Python3.4

#In the batch file,
# - Add after "@echo off": 
#     set WD="%~dp0"
# - Replace "echo %* > %TEMP%\params.txt" with: 
#     echo %WD% %* > %TEMP%\params.txt

param (

  [Parameter(Mandatory=$true)]
  [string] $WorkingDir,

  [Parameter(Mandatory=$true)]
  [string] $LogDir,

  [Parameter(Mandatory=$false)]
  [switch] $recurse  

)

function convert-dir {
  param ( $Log )

  $newlog = $Log.ToLower()
  $newlog = $newlog -replace "\\","/" 
  $newlog = $newlog -replace ":/","/"
  """/cygdrive/$newlog"""
}

function chew-log {
  param ( $Log )

  #Run the Python script
  $logDir = convert-dir($Log)
  $dosDir =$([regex]"^(.*)\\.*$").matches($log).groups[1].value
  write-host "Running chew-log on $Log..."
  $args = "$CygwinWorkingDir/chew-log.py $logDir"
  Start-Process -FilePath "C:\Cygwin\bin\mintty.exe" -ArgumentList $args -Wait
  if (!(test-path "$Log.index")) {
      $MyFile = Get-Content $Log
      [System.IO.File]::WriteAllLines("$dosDir\temp.txt", $MyFile)
      $tempargs = "$CygwinWorkingDir/chew-log.py $(convert-dir("$dosDir\temp.txt"))"
      Start-Process -FilePath "C:\Cygwin\bin\mintty.exe" -ArgumentList $tempargs -Wait
      rename-item -Force "$dosDir\temp.txt.index" "$Log.index"
	  remove-item -Force "$dosDir\temp.txt"
  }
}

### Main routine ###
write-host "Working Dir = $WorkingDir"
$CygwinWorkingDir = convert-dir $WorkingDir
$IsDirectory = (get-item $LogDir) -is [System.IO.DirectoryInfo]
if (!$IsDirectory) {
    chew-log "$LogDir"
    $args = "$CygwinWorkingDir/remove-words.py $(convert-dir "$LogDir.index") $CygwinWorkingDir"
    Start-Process -FilePath "C:\Cygwin\bin\mintty.exe" -ArgumentList $args -Wait
} elseif ($IsDirectory) {
    gci "$LogDir" -recurse -Exclude "filelist.index" | where { !$_.PSisContainer } | select @{Name="Name"; Expression={$_.fullname.substring($LogDir.length+1)} }, Length, LastWriteTime | out-file "$LogDir\filelist.index" -encoding ascii
    if ($recurse) {
      gci -recurse "$LogDir" -Exclude "*.index" | sort -Property Length |% { chew-log $_.FullName }
      gci -recurse "$LogDir\*.index" -Exclude "filelist.index" |% { get-content $_.FullName -Raw | Out-File -Append -Encoding ascii "$LogDir\summary.txt" }
    } else {
      gci "$LogDir" -Exclude "*.index" | sort -Property Length |% { chew-log $_.FullName }
      gci "$LogDir\*.index" -Exclude "filelist.index" |% { get-content $_.FullName -Raw | Out-File -Append -Encoding ascii "$LogDir\summary.txt" }
    }
    chew-log "$LogDir\summary.txt"
    $args = "$CygwinWorkingDir/remove-words.py $(convert-dir "$LogDir\summary.txt.index") $CygwinWorkingDir"
    Start-Process -FilePath "C:\Cygwin\bin\mintty.exe" -ArgumentList $args -Wait
} else {
    write-host "Argument outside universe of discourse (not a file or directory)."
}
write-host "Done"
}

invoke-expression "main1 $(Get-Content $env:TEMP\params.txt)"
===========================================================================
:startCode
echo %WD% %* > %TEMP%\params.txt

powershell.exe -NoLogo -NoProfile -EncodedCommand ZgB1AG4AYwB0AGkAbwBuACAAbQBhAGkAbgAxACAAewANAAoAIAAgACMAIABSAGUAcQB1AGkAcgBlAHMAIABDAHkAZwB3AGkAbgAgAHcAaQB0AGgAIABQAHkAdABoAG8AbgAzAC4ANAANAAoADQAKACMASQBuACAAdABoAGUAIABiAGEAdABjAGgAIABmAGkAbABlACwADQAKACMAIAAtACAAQQBkAGQAIABhAGYAdABlAHIAIAAiAEAAZQBjAGgAbwAgAG8AZgBmACIAOgAgAA0ACgAjACAAIAAgACAAIABzAGUAdAAgAFcARAA9ACIAVgA6AFwAQwBJAEEAVQBcAEkAVABTAFAAXABUAG8AbwBsAHMAXABsAG8AZwAgAHIAZQBkAGEAYwB0AGkAbwBuACIADQAKACMAIAAtACAAUgBlAHAAbABhAGMAZQAgACIAZQBjAGgAbwAgACUAKgAgAD4AIAAlAFQARQBNAFAAJQBcAHAAYQByAGEAbQBzAC4AdAB4AHQAIgAgAHcAaQB0AGgAOgAgAA0ACgAjACAAIAAgACAAIABlAGMAaABvACAAJQBXAEQAJQAgACUAKgAgAD4AIAAlAFQARQBNAFAAJQBcAHAAYQByAGEAbQBzAC4AdAB4AHQADQAKAA0ACgBwAGEAcgBhAG0AIAAoAA0ACgANAAoAIAAgAFsAUABhAHIAYQBtAGUAdABlAHIAKABNAGEAbgBkAGEAdABvAHIAeQA9ACQAdAByAHUAZQApAF0ADQAKACAAIABbAHMAdAByAGkAbgBnAF0AIAAkAFcAbwByAGsAaQBuAGcARABpAHIALAANAAoADQAKACAAIABbAFAAYQByAGEAbQBlAHQAZQByACgATQBhAG4AZABhAHQAbwByAHkAPQAkAHQAcgB1AGUAKQBdAA0ACgAgACAAWwBzAHQAcgBpAG4AZwBdACAAJABMAG8AZwBEAGkAcgAsAA0ACgANAAoAIAAgAFsAUABhAHIAYQBtAGUAdABlAHIAKABNAGEAbgBkAGEAdABvAHIAeQA9ACQAZgBhAGwAcwBlACkAXQANAAoAIAAgAFsAcwB3AGkAdABjAGgAXQAgACQAcgBlAGMAdQByAHMAZQAgACAADQAKAA0ACgApAA0ACgANAAoAZgB1AG4AYwB0AGkAbwBuACAAYwBvAG4AdgBlAHIAdAAtAGQAaQByACAAewANAAoAIAAgAHAAYQByAGEAbQAgACgAIAAkAEwAbwBnACAAKQANAAoADQAKACAAIAAkAG4AZQB3AGwAbwBnACAAPQAgACQATABvAGcALgBUAG8ATABvAHcAZQByACgAKQANAAoAIAAgACQAbgBlAHcAbABvAGcAIAA9ACAAJABuAGUAdwBsAG8AZwAgAC0AcgBlAHAAbABhAGMAZQAgACIAXABcACIALAAiAC8AIgAgAA0ACgAgACAAJABuAGUAdwBsAG8AZwAgAD0AIAAkAG4AZQB3AGwAbwBnACAALQByAGUAcABsAGEAYwBlACAAIgA6AC8AIgAsACIALwAiAA0ACgAgACAAIgAiACIALwBjAHkAZwBkAHIAaQB2AGUALwAkAG4AZQB3AGwAbwBnACIAIgAiAA0ACgB9AA0ACgANAAoAZgB1AG4AYwB0AGkAbwBuACAAYwBoAGUAdwAtAGwAbwBnACAAewANAAoAIAAgAHAAYQByAGEAbQAgACgAIAAkAEwAbwBnACAAKQANAAoADQAKACAAIAAjAFIAdQBuACAAdABoAGUAIABQAHkAdABoAG8AbgAgAHMAYwByAGkAcAB0AA0ACgAgACAAJABsAG8AZwBEAGkAcgAgAD0AIABjAG8AbgB2AGUAcgB0AC0AZABpAHIAKAAkAEwAbwBnACkADQAKACAAIAAkAGQAbwBzAEQAaQByACAAPQAkACgAWwByAGUAZwBlAHgAXQAiAF4AKAAuACoAKQBcAFwALgAqACQAIgApAC4AbQBhAHQAYwBoAGUAcwAoACQAbABvAGcAKQAuAGcAcgBvAHUAcABzAFsAMQBdAC4AdgBhAGwAdQBlAA0ACgAgACAAdwByAGkAdABlAC0AaABvAHMAdAAgACIAUgB1AG4AbgBpAG4AZwAgAGMAaABlAHcALQBsAG8AZwAgAG8AbgAgACQATABvAGcALgAuAC4AIgANAAoAIAAgACQAYQByAGcAcwAgAD0AIAAiACQAQwB5AGcAdwBpAG4AVwBvAHIAawBpAG4AZwBEAGkAcgAvAGMAaABlAHcALQBsAG8AZwAuAHAAeQAgACQAbABvAGcARABpAHIAIgANAAoAIAAgAFMAdABhAHIAdAAtAFAAcgBvAGMAZQBzAHMAIAAtAEYAaQBsAGUAUABhAHQAaAAgACIAQwA6AFwAQwB5AGcAdwBpAG4AXABiAGkAbgBcAG0AaQBuAHQAdAB5AC4AZQB4AGUAIgAgAC0AQQByAGcAdQBtAGUAbgB0AEwAaQBzAHQAIAAkAGEAcgBnAHMAIAAtAFcAYQBpAHQADQAKACAAIABpAGYAIAAoACEAKAB0AGUAcwB0AC0AcABhAHQAaAAgACIAJABMAG8AZwAuAGkAbgBkAGUAeAAiACkAKQAgAHsADQAKACAAIAAgACAAIAAgACQATQB5AEYAaQBsAGUAIAA9ACAARwBlAHQALQBDAG8AbgB0AGUAbgB0ACAAJABMAG8AZwANAAoAIAAgACAAIAAgACAAWwBTAHkAcwB0AGUAbQAuAEkATwAuAEYAaQBsAGUAXQA6ADoAVwByAGkAdABlAEEAbABsAEwAaQBuAGUAcwAoACIAJABkAG8AcwBEAGkAcgBcAHQAZQBtAHAALgB0AHgAdAAiACwAIAAkAE0AeQBGAGkAbABlACkADQAKACAAIAAgACAAIAAgACQAdABlAG0AcABhAHIAZwBzACAAPQAgACIAJABDAHkAZwB3AGkAbgBXAG8AcgBrAGkAbgBnAEQAaQByAC8AYwBoAGUAdwAtAGwAbwBnAC4AcAB5ACAAJAAoAGMAbwBuAHYAZQByAHQALQBkAGkAcgAoACIAJABkAG8AcwBEAGkAcgBcAHQAZQBtAHAALgB0AHgAdAAiACkAKQAiAA0ACgAgACAAIAAgACAAIABTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAALQBGAGkAbABlAFAAYQB0AGgAIAAiAEMAOgBcAEMAeQBnAHcAaQBuAFwAYgBpAG4AXABtAGkAbgB0AHQAeQAuAGUAeABlACIAIAAtAEEAcgBnAHUAbQBlAG4AdABMAGkAcwB0ACAAJAB0AGUAbQBwAGEAcgBnAHMAIAAtAFcAYQBpAHQADQAKACAAIAAgACAAIAAgAHIAZQBuAGEAbQBlAC0AaQB0AGUAbQAgAC0ARgBvAHIAYwBlACAAIgAkAGQAbwBzAEQAaQByAFwAdABlAG0AcAAuAHQAeAB0AC4AaQBuAGQAZQB4ACIAIAAiACQATABvAGcALgBpAG4AZABlAHgAIgANAAoACQAgACAAcgBlAG0AbwB2AGUALQBpAHQAZQBtACAALQBGAG8AcgBjAGUAIAAiACQAZABvAHMARABpAHIAXAB0AGUAbQBwAC4AdAB4AHQAIgANAAoAIAAgAH0ADQAKAH0ADQAKAA0ACgAjACMAIwAgAE0AYQBpAG4AIAByAG8AdQB0AGkAbgBlACAAIwAjACMADQAKAHcAcgBpAHQAZQAtAGgAbwBzAHQAIAAiAFcAbwByAGsAaQBuAGcAIABEAGkAcgAgAD0AIAAkAFcAbwByAGsAaQBuAGcARABpAHIAIgANAAoAJABDAHkAZwB3AGkAbgBXAG8AcgBrAGkAbgBnAEQAaQByACAAPQAgAGMAbwBuAHYAZQByAHQALQBkAGkAcgAgACQAVwBvAHIAawBpAG4AZwBEAGkAcgANAAoAJABJAHMARABpAHIAZQBjAHQAbwByAHkAIAA9ACAAKABnAGUAdAAtAGkAdABlAG0AIAAkAEwAbwBnAEQAaQByACkAIAAtAGkAcwAgAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBEAGkAcgBlAGMAdABvAHIAeQBJAG4AZgBvAF0ADQAKAGkAZgAgACgAIQAkAEkAcwBEAGkAcgBlAGMAdABvAHIAeQApACAAewANAAoAIAAgACAAIABjAGgAZQB3AC0AbABvAGcAIAAiACQATABvAGcARABpAHIAIgANAAoAIAAgACAAIAAkAGEAcgBnAHMAIAA9ACAAIgAkAEMAeQBnAHcAaQBuAFcAbwByAGsAaQBuAGcARABpAHIALwByAGUAbQBvAHYAZQAtAHcAbwByAGQAcwAuAHAAeQAgACQAKABjAG8AbgB2AGUAcgB0AC0AZABpAHIAIAAiACQATABvAGcARABpAHIALgBpAG4AZABlAHgAIgApACAAJABDAHkAZwB3AGkAbgBXAG8AcgBrAGkAbgBnAEQAaQByACIADQAKACAAIAAgACAAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgAC0ARgBpAGwAZQBQAGEAdABoACAAIgBDADoAXABDAHkAZwB3AGkAbgBcAGIAaQBuAFwAbQBpAG4AdAB0AHkALgBlAHgAZQAiACAALQBBAHIAZwB1AG0AZQBuAHQATABpAHMAdAAgACQAYQByAGcAcwAgAC0AVwBhAGkAdAANAAoAfQAgAGUAbABzAGUAaQBmACAAKAAkAEkAcwBEAGkAcgBlAGMAdABvAHIAeQApACAAewANAAoAIAAgACAAIABnAGMAaQAgACIAJABMAG8AZwBEAGkAcgAiACAALQByAGUAYwB1AHIAcwBlACAALQBFAHgAYwBsAHUAZABlACAAIgBmAGkAbABlAGwAaQBzAHQALgBpAG4AZABlAHgAIgAgAHwAIAB3AGgAZQByAGUAIAB7ACAAIQAkAF8ALgBQAFMAaQBzAEMAbwBuAHQAYQBpAG4AZQByACAAfQAgAHwAIABzAGUAbABlAGMAdAAgAEAAewBOAGEAbQBlAD0AIgBOAGEAbQBlACIAOwAgAEUAeABwAHIAZQBzAHMAaQBvAG4APQB7ACQAXwAuAGYAdQBsAGwAbgBhAG0AZQAuAHMAdQBiAHMAdAByAGkAbgBnACgAJABMAG8AZwBEAGkAcgAuAGwAZQBuAGcAdABoACsAMQApAH0AIAB9ACwAIABMAGUAbgBnAHQAaAAsACAATABhAHMAdABXAHIAaQB0AGUAVABpAG0AZQAgAHwAIABvAHUAdAAtAGYAaQBsAGUAIAAiACQATABvAGcARABpAHIAXABmAGkAbABlAGwAaQBzAHQALgBpAG4AZABlAHgAIgAgAC0AZQBuAGMAbwBkAGkAbgBnACAAYQBzAGMAaQBpAA0ACgAgACAAIAAgAGkAZgAgACgAJAByAGUAYwB1AHIAcwBlACkAIAB7AA0ACgAgACAAIAAgACAAIABnAGMAaQAgAC0AcgBlAGMAdQByAHMAZQAgACIAJABMAG8AZwBEAGkAcgAiACAALQBFAHgAYwBsAHUAZABlACAAIgAqAC4AaQBuAGQAZQB4ACIAIAB8ACAAcwBvAHIAdAAgAC0AUAByAG8AcABlAHIAdAB5ACAATABlAG4AZwB0AGgAIAB8ACUAIAB7ACAAYwBoAGUAdwAtAGwAbwBnACAAJABfAC4ARgB1AGwAbABOAGEAbQBlACAAfQANAAoAIAAgACAAIAAgACAAZwBjAGkAIAAtAHIAZQBjAHUAcgBzAGUAIAAiACQATABvAGcARABpAHIAXAAqAC4AaQBuAGQAZQB4ACIAIAAtAEUAeABjAGwAdQBkAGUAIAAiAGYAaQBsAGUAbABpAHMAdAAuAGkAbgBkAGUAeAAiACAAfAAlACAAewAgAGcAZQB0AC0AYwBvAG4AdABlAG4AdAAgACQAXwAuAEYAdQBsAGwATgBhAG0AZQAgAC0AUgBhAHcAIAB8ACAATwB1AHQALQBGAGkAbABlACAALQBBAHAAcABlAG4AZAAgAC0ARQBuAGMAbwBkAGkAbgBnACAAYQBzAGMAaQBpACAAIgAkAEwAbwBnAEQAaQByAFwAcwB1AG0AbQBhAHIAeQAuAHQAeAB0ACIAIAB9AA0ACgAgACAAIAAgAH0AIABlAGwAcwBlACAAewANAAoAIAAgACAAIAAgACAAZwBjAGkAIAAiACQATABvAGcARABpAHIAIgAgAC0ARQB4AGMAbAB1AGQAZQAgACIAKgAuAGkAbgBkAGUAeAAiACAAfAAgAHMAbwByAHQAIAAtAFAAcgBvAHAAZQByAHQAeQAgAEwAZQBuAGcAdABoACAAfAAlACAAewAgAGMAaABlAHcALQBsAG8AZwAgACQAXwAuAEYAdQBsAGwATgBhAG0AZQAgAH0ADQAKACAAIAAgACAAIAAgAGcAYwBpACAAIgAkAEwAbwBnAEQAaQByAFwAKgAuAGkAbgBkAGUAeAAiACAALQBFAHgAYwBsAHUAZABlACAAIgBmAGkAbABlAGwAaQBzAHQALgBpAG4AZABlAHgAIgAgAHwAJQAgAHsAIABnAGUAdAAtAGMAbwBuAHQAZQBuAHQAIAAkAF8ALgBGAHUAbABsAE4AYQBtAGUAIAAtAFIAYQB3ACAAfAAgAE8AdQB0AC0ARgBpAGwAZQAgAC0AQQBwAHAAZQBuAGQAIAAtAEUAbgBjAG8AZABpAG4AZwAgAGEAcwBjAGkAaQAgACIAJABMAG8AZwBEAGkAcgBcAHMAdQBtAG0AYQByAHkALgB0AHgAdAAiACAAfQANAAoAIAAgACAAIAB9AA0ACgAgACAAIAAgAGMAaABlAHcALQBsAG8AZwAgACIAJABMAG8AZwBEAGkAcgBcAHMAdQBtAG0AYQByAHkALgB0AHgAdAAiAA0ACgAgACAAIAAgACQAYQByAGcAcwAgAD0AIAAiACQAQwB5AGcAdwBpAG4AVwBvAHIAawBpAG4AZwBEAGkAcgAvAHIAZQBtAG8AdgBlAC0AdwBvAHIAZABzAC4AcAB5ACAAJAAoAGMAbwBuAHYAZQByAHQALQBkAGkAcgAgACIAJABMAG8AZwBEAGkAcgBcAHMAdQBtAG0AYQByAHkALgB0AHgAdAAuAGkAbgBkAGUAeAAiACkAIAAkAEMAeQBnAHcAaQBuAFcAbwByAGsAaQBuAGcARABpAHIAIgANAAoAIAAgACAAIABTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAALQBGAGkAbABlAFAAYQB0AGgAIAAiAEMAOgBcAEMAeQBnAHcAaQBuAFwAYgBpAG4AXABtAGkAbgB0AHQAeQAuAGUAeABlACIAIAAtAEEAcgBnAHUAbQBlAG4AdABMAGkAcwB0ACAAJABhAHIAZwBzACAALQBXAGEAaQB0AA0ACgB9ACAAZQBsAHMAZQAgAHsADQAKACAAIAAgACAAdwByAGkAdABlAC0AaABvAHMAdAAgACIAQQByAGcAdQBtAGUAbgB0ACAAbwB1AHQAcwBpAGQAZQAgAHUAbgBpAHYAZQByAHMAZQAgAG8AZgAgAGQAaQBzAGMAbwB1AHIAcwBlACAAKABuAG8AdAAgAGEAIABmAGkAbABlACAAbwByACAAZABpAHIAZQBjAHQAbwByAHkAKQAuACIADQAKAH0ADQAKAHcAcgBpAHQAZQAtAGgAbwBzAHQAIAAiAEQAbwBuAGUAIgANAAoAfQANAAoADQAKAGkAbgB2AG8AawBlAC0AZQB4AHAAcgBlAHMAcwBpAG8AbgAgACIAbQBhAGkAbgAxACAAJAAoAEcAZQB0AC0AQwBvAG4AdABlAG4AdAAgACQAZQBuAHYAOgBUAEUATQBQAFwAcABhAHIAYQBtAHMALgB0AHgAdAApACIA

del %TEMP%\params.txt
