param (

	[Parameter(Mandatory=$true)]
	[string] $Log

)

$hexArray=New-Object System.Collections.ArrayList
$hexRegex=[regex]"([0-9a-fA-F]{16,})"

function make-new-object {
  param ( $hex, $ascii )

  $object = New-Object System.Object
  $object | Add-Member -type NoteProperty -name Hex -Value $hex
  $object | Add-Member -type NoteProperty -name Ascii -Value $ascii
  $object
}

function convert-hex2ascii {
  param ( $hex )

  for ($i=0; $i -lt $hex.Length; $i+=2) { 
    $word += [char][int]::Parse($hex.substring($i,2),'HexNumber') 
  }
  #write-host -ForegroundColor Green $hex
  #write-host -ForegroundColor Yellow $word
  if ( !( $([regex]"^\W+$").Match($word).Success ) ) {
    $hexArray.Add($(make-new-object $hex $word)) | Out-Null
  }
}

Get-Content $Log |% {
  $a = $hexRegex.Match($_)
  if ($a.Success) {
    for ($i=1; $i -lt $a.Groups.Count; $i++) {
      convert-hex2ascii $a.Groups[$i].Value
    }
  }
}

$hexArray | Out-GridView

# SIG # Begin signature block
# MIIWNQYJKoZIhvcNAQcCoIIWJjCCFiICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUsgS/mBYhJ1TYY+sAaApBnHWP
# eV+gghODMIIGTDCCBDSgAwIBAgIKTLYQZwAAAAAi5TANBgkqhkiG9w0BAQsFADBt
# MQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQL
# EwNET0oxDDAKBgNVBAsTA0ZCSTEMMAoGA1UECxMDUEtJMRowGAYDVQQDExFDSklT
# IENKSVNVTkVUIENBMTAeFw0xODA5MDQxNzIzNTlaFw0xOTA5MDQxNzIzNTlaMIGe
# MRMwEQYKCZImiZPyLGQBGRYDRkJJMRcwFQYKCZImiZPyLGQBGRYHT01OSU5FVDER
# MA8GA1UECxMIRU5EVVNFUlMxDTALBgNVBAsTBENKSVMxEzARBgNVBAsTCk9wcyBC
# cmFuY2gxDTALBgNVBAsTBElUTVMxDTALBgNVBAsTBENJQVUxGTAXBgNVBAMTEEty
# YWpld3NraSwgTGVvIEowggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDu
# 6VuIfdEP6toZxHylzuJWpY626doLvuXTsJiZls/LlTASVWysV2/iqAlQCu/IVVqo
# r6Cv7IAnSXsRYlIyxp/x0a5qaTuGiFk3C8fC8JabMrFAJr79Imk2jyK4oMgfAi83
# qckfun1yn3VSJwG5KO3PD4To7Td8ms8sfVVkpT7/f+yv4mqtlkgVp8uqBGePqGLQ
# /NqIYuy+JzfqcK2y3mvm8bW66YawlMNTmkXO7nPtemxkIeJu5e+BTLnOyzBQKWJW
# GoFVxsuLtqHL1pLmpGDqj65MxrQGxNNEJuFpsaEZ77x4+nrwxtxrJc0s+chjA5W+
# hJPYO9+lexwSOv3DVtqhAgMBAAGjggG6MIIBtjA+BgkrBgEEAYI3FQcEMTAvBicr
# BgEEAYI3FQiBzIBIh5bDboLNgzqBhdIBgrKXJYFbhdKCUoeXhWwCAWQCAQQwEwYD
# VR0lBAwwCgYIKwYBBQUHAwMwCwYDVR0PBAQDAgeAMBsGCSsGAQQBgjcVCgQOMAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFAhC+T5ATtAyPUlIiHbWV4uHQf7QMB8GA1Ud
# IwQYMBaAFKARwP9wWEmxQJH2O1iRZ8ITGCUBMEcGA1UdHwRAMD4wPKA6oDiGNmh0
# dHA6Ly9wa2kuY2ppcy5mYmkvY2ppc3VuZXQvQ0pJUyUyMENKSVNVTkVUJTIwQ0Ex
# LmNybDB4BggrBgEFBQcBAQRsMGowJAYIKwYBBQUHMAGGGGh0dHA6Ly9wa2kuY2pp
# cy5mYmkvb2NzcDBCBggrBgEFBQcwAoY2aHR0cDovL3BraS5jamlzLmZiaS9jamlz
# dW5ldC9DSklTJTIwQ0pJU1VORVQlMjBDQTEuY3J0MDIGA1UdEQQrMCmgJwYKKwYB
# BAGCNxQCA6AZDBdsamtyYWpld3NraUBPTU5JTkVULkZCSTANBgkqhkiG9w0BAQsF
# AAOCAgEAfwJlSBaI+UoaIAhffuc5IoHzEYSqNVP2S3LRkLBRRvRSEAHNLdVOqbUv
# 3LTuw8a/TiCdNs4FuhqHtDD/WLpWm8mgb6N6CNtLtCvG6zSGGgou819je4eH5gma
# V2xpBmTbWsrV3/6WTLbfqtehPmMEzG9iFzbLwdQsJ5gn4Ab5xQA6UiTlJT0L4s22
# 62q2kuWBN2gGLONcbA/Q0TKkUfqCM0R69hujWpI0YPhAEFqN/eEvrnVT22RuU1Sa
# fSORa0PJQ8Y3hksB2+tDxGZF9s3ePcXrnn/5bLkZ3kM3x+GERfBtImMMG7cpQy0j
# ycTihtrjOSU6WvjH1mzKMHZlTri//XonKtRoCpJeA07qaqKgRgcNVYVqKqQbrmCw
# ys7M3XBnt4oZq0E7EAXaBH2aVx7L4t3VVdd1t/Urw4bIDsE5CGxO5aah8ysmhKm7
# JMEL0Fll4tFwKocmbzkXBM+Lf2/bgLu6rKkGhx5xgMtBqUvlxuW0TH9oyVGRLSxF
# Ry9ZbGXsVcTCIoPryPZ2tJfO7sCyLoGJNCN0l9wgE2aCj84jfdyded5eFVQWB44/
# Shqx4HM8iMsNJKOwZbIz6dk42chgo6xMSnyVnEk9tGeyDMY2XZQ7IJP3on/QB14L
# F7ZLbt2Xb+keT7cT/zcElcA6SSTrAcWETYEnCmEQegvg/uCVtaswggZZMIIEQaAD
# AgECAgoZ3MUdAAIAAABOMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNVBAYTAlVTMRgw
# FgYDVQQKEw9VLlMuIEdPVkVSTk1FTlQxDDAKBgNVBAsTA0RPSjEMMAoGA1UECxMD
# RkJJMQwwCgYDVQQLEwNQS0kxEjAQBgNVBAMTCUNKSVMgQ0EtMTAeFw0xNDAzMDQy
# MDIzMzdaFw0yMDAzMDQyMDMzMzdaMG0xCzAJBgNVBAYTAlVTMRgwFgYDVQQKEw9V
# LlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0RPSjEMMAoGA1UECxMDRkJJMQwwCgYD
# VQQLEwNQS0kxGjAYBgNVBAMTEUNKSVMgQ0pJU1VORVQgQ0ExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEArcGhCF+QCz3P1kEujmzwoVAeceeK3rGLMMGP
# +QQ9shJyPiish1pUCF+0g5N82wfvHI6rwxJGmyqGgZO/Eis9HIqVeFIqq6rqAK5T
# nPiMeUdXE9SNpr/PBUA21kNuINASO/B+3cuj0/NpRpj1pnMfkiPNMRhxhPMI4zf5
# LG6yYC2JkS64AGx8GuqvtmOmeLs1+RERqmb96rybZFQo0zNkhsrU1EkNTNIZ11o4
# StiYYGQ3cT30tb8fs28Nc0zzKaisb0AYhRTOKhIW+voh1u3Q2zzFerbEVfRp5uY3
# aV1K/+41ySXrq+1ZshQtKoQZII5il3BwQSxw0eo6h4C5+qkfkrSvnQLv88sgnh7P
# 1+F7hrVJwmacEqbVBzwTBpWIVzydQfHizxcwtIJlZXeMqLqbM4Z8Te6WCQSrTo0s
# 8MjKpqtJ6pKBXH/vWILzc2QxwC34c1oWPE1ofJcxd3ctYzVytSxdBKfBXCa+PLGm
# rK5FYTiA8h0BUrsYklholehITmv4EapoDuci0qVs7xC2zsd0EcJkaXl3LJ2VkuBL
# RgeZArytPjXlfrM9j6tJHrNDpSXPAsQeM97nRgip3D1ne8A9aXbcfXAsS/yVzV2J
# 5IYRpldGs67Sh0esbuMuZa3B0piOJr+FKrDs6zv9uMzdIQjMLDJ+FTt8RPc/9NUt
# jSx/Zk8CAwEAAaOCAQEwgf4wEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFKAR
# wP9wWEmxQJH2O1iRZ8ITGCUBMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsG
# A1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFEJ4K1rvlGyP
# Wn5y/S4CMSqUpyP9MDsGA1UdHwQ0MDIwMKAuoCyGKmh0dHA6Ly9wa2kuY2ppcy5m
# YmkvaW50L0NKSVMlMjBDQS0xKDIpLmNybDA0BggrBgEFBQcBAQQoMCYwJAYIKwYB
# BQUHMAGGGGh0dHA6Ly9wa2kuY2ppcy5mYmkvb2NzcDANBgkqhkiG9w0BAQsFAAOC
# AgEAi2VXfJ+RLZ2X7bUgwDdtZ2cvMWwMIXUKh0QXdZUkLsotwEquCcUh2gCA4cH2
# ehtxN/ctn1o4qWMsvE+Tx4u8PjsAXIquYdmdrPNW38/shSt1zKCh2VLpvqfxOOdT
# jmDCODVxQ4ScyF8dNqnsyc+EzD3qa6VOGA8F8XAjhppVhXSrGJtt8Lweo0qnRmhQ
# LFZJtCzdNgKocEo4BohWPSwkJCX7kHrYhw+w67IsMycNJFEU5c1iLiKAD82QRvJC
# C6llZmyt7xkUuGP44t3h52xNmgMRXepH+NYVOGsyzgBiHZE4RG4+6LFW6BwBDOY8
# 2e5e35OK5RctXfLW1EWzjSkbic3suZA5k3e0Dj9EBcMbX1tPNrxipkLcuF0g0aI9
# 4RgKvDv1ba7o80ZgMEF9EKiMjiU8cJTXD0VlXIwmDC6gIdx0/M66ZkMW8CmWBmkY
# suM+lhhGJWtvC1kL1p0lpkWKGEJuqdEHTb7T/3Z/FyxtN8wVJLYcYgk68GA+L1dw
# VpAJBhqRueNo6udycjZLkfbiYVDGpp8eLAI2l/CmNA+cve7coh36Du2ueIE82mHF
# Y3zhSeY/pmnc2sDkh2cxsykUdZRo2v1eMkQ3TImojyNAtKAQQxfUDY1Q9tREhgDT
# LtsAI37LtqwodwMIhfoJf7qJ9wVT83/bYZl+u+BhQEVCJicwggbSMIIEuqADAgEC
# AgphF+NqAAEAAAAUMA0GCSqGSIb3DQEBCwUAMGoxCzAJBgNVBAYTAlVTMRgwFgYD
# VQQKEw9VLlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0RPSjEMMAoGA1UECxMDRkJJ
# MQwwCgYDVQQLEwNQS0kxFzAVBgNVBAMTDkNKSVMgUk9PVCBDQSAxMB4XDTE0MDIy
# ODE2MTkxNFoXDTIzMDIyODE2MjkxNFowZTELMAkGA1UEBhMCVVMxGDAWBgNVBAoT
# D1UuUy4gR09WRVJOTUVOVDEMMAoGA1UECxMDRE9KMQwwCgYDVQQLEwNGQkkxDDAK
# BgNVBAsTA1BLSTESMBAGA1UEAxMJQ0pJUyBDQS0xMIICIjANBgkqhkiG9w0BAQEF
# AAOCAg8AMIICCgKCAgEA440wrJh4oHpzMwAer5byk1cJm/50c8Bf+Bm9hb2HpYVg
# 7lPHa2odECQm6stcRQUj6mZdp+HbcSZ/CHo57CQt7+k6MjJbTfD6peH2+MyuA70q
# sZgnn4xsmiUf7Ehjxbmm/QQBg4l2EzE2vJOnOEYAignfpkoWovAEBiF6lRe5Bo1F
# c/Yl6ITzYvDRR1wZnTj1UKJQ286Q4FEBzjj87VyTsrEoHZLwahwfNpTEgd6840zp
# Imx3qZEH0Zmwr7f4POtgAag9zOGULOdhx8TlKY2I8FP5EhYolOQ/cYpJjrF3L1AC
# vAozMLWP07QPwByvDifKdzwxKW2bE7Y4bhpLY7jRloG5edRFNPqE0cPyGWYIC+lT
# KJYkydLdfq/AOm2wJ/0Zy27nSIt0V4MZdbqhFeYiNyCy4eRNPf1LSxZJgiZIo1CV
# 1vHfE6e7xRcNN6+RjlBAqFqSW0V7vrDf6kMb23N6MyYtT2K9IuVts2yUM2svSou0
# palfo9Qo/Cpfd+czKz1CLrNVGywQ8g/X9LNuG8/CuK94GLlqrvmKW9G2Ldb168xI
# gAU+hIIklfuokBhuuCgsWDbbxMJWSlfZLQKjZW7Pchl/Fixot2dYKqrIMUOII9dM
# /WIwZNiD1DU/yLOOV9ohpyyq7YZj7Qx5fe3zfXATC6ad12AUjr4tnpAfDoR9kVMC
# AwEAAaOCAX0wggF5MBIGCSsGAQQBgjcVAQQFAgMCAAIwIwYJKwYBBAGCNxUCBBYE
# FPRaZAKGq9EsuDfEbLaXf96Py+z4MB0GA1UdDgQWBBRCeCta75Rsj1p+cv0uAjEq
# lKcj/TB+BgNVHSAEdzB1MHMGCmCGSAFlAwIBAwYwZTA6BggrBgEFBQcCAjAuHiwA
# TABlAGcAYQBsACAAUABvAGwAaQBjAHkAIABTAHQAYQB0AGUAbQBlAG4AdDAnBggr
# BgEFBQcCARYbaHR0cDovL3BraS5jamlzLmZiaS9jcHMudHh0MBkGCSsGAQQBgjcU
# AgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8G
# A1UdIwQYMBaAFNIY1tDN2lwlpxz2Cz2XAftFmn0FMEUGA1UdHwQ+MDwwOqA4oDaG
# NGh0dHA6Ly9wa2kuY2ppcy5mYmkvcm9vdC9DSklTJTIwUk9PVCUyMENBJTIwMSgx
# KS5jcmwwDQYJKoZIhvcNAQELBQADggIBABTygYz5G60kY41HrnsvRAFU+FpQMpDl
# xCA0VVGHgs1CaGcHuhv3S4y+s4OT8jLeR+rTYaeldL1gPNYnu7kQy2Ffya9gKUpi
# Czco27E/CD+QZcfWVWyzOqqxX62PO63fIZjoW38UyJl4exr9s5uFAmAHjzWBlb9+
# KsvoUXyRVa5xHnBoAo7zlppvuc8nKSEXqMPzQrcjxNfIbmjlb+CRskdsmD5Rkjm8
# oP0KXifxL17FBDGlDKm1LfGFO4N+NXtcn3oGJrB+QuPMabZ2qU/XjuZC8BmA9LRD
# V33on+9iMKgaXykp8W9CzE45IgBgFz/KxsY8CPaKGe2R4LClvoQ9IhRukoFNn4+m
# 5dE83mUNdbOu38pGEousaqtbvjBph4GsDhXg0SirCqXc1ifEErIODHaKKIHMnas6
# oaCx3YwUcPpPbS+zc+HIfXdBwfLSy3rWfFm6Gr+Gb7V3t5I0l/SToYvRbSVUsbtR
# trOIlM5EDxBlEHWrJ5pnxn3lNvg9ZR4V5/ugxTNnVJq49BA7C3GtXJyXSaTvCd8D
# Y2vhlYe/GdZiNqDcFCV72mwyUqNrch9UcBv61slJmHbm1o1cjMTY0vAoI7SzG+Lk
# jHwfoBBtgygihdoWmfoNQCPD+4muL/gQ86i1YsCAFNO4o+muVQGOFNuinIMcfTwc
# wda280lA1yw7MYICHDCCAhgCAQEwezBtMQswCQYDVQQGEwJVUzEYMBYGA1UEChMP
# VS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNET0oxDDAKBgNVBAsTA0ZCSTEMMAoG
# A1UECxMDUEtJMRowGAYDVQQDExFDSklTIENKSVNVTkVUIENBMQIKTLYQZwAAAAAi
# 5TAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAjBgkqhkiG9w0BCQQxFgQUeOhL6rlhSAntRrzRoVAuSEm5SDAwDQYJKoZIhvcN
# AQEBBQAEggEAsusS7VvzYvQO6ME0OeXu3P9CYMtsZR3qcq4gmx+JAw3HzH+0Yl6+
# rerEeq415LPnY10KkPwP14pMB3aVaGx3F436kgFGsNKEePmw+q14reA2FZozqIZo
# iiCUcWSi75CbSu4YZYmlWNkuY4zESBuU8vItlXyNG/miOFeDFvp6SZCLGuQvLWjJ
# QI135gncTDSZk7zkdaYdlcFwpbNvo9NFmNu2JMjBBx7RrrFwQ52H4PXfIsyjS2h4
# f7dBrW7FU5ljH4oTL8aKPG2GQPPxinuH16YlEdgqhv/hO6w7xKUK4YsmLz9/LseV
# +JiIfywPQgwuA3hKXdecRnDBgF8tOzP9XQ==
# SIG # End signature block
